_format_version: "2.1"

services:
- name: auth-service
  url: http://172.18.0.6:8181
  routes:
  - name: sign-up
    paths:
    - /auth/v1/signup

- name: user-service
  url: http://172.18.0.5:8282
  routes:
    - name: get-user
      paths:
      - /user/v1/getUser